### ISSUE TITLE
Insecured Fetch on Production

### ISSUE THREAD

**Issue by moseslucas** [zhso/reverse-geocoding#6]
When using in production, it seems like that the remote url its fetching is using `http` instead of `https`

![httpsgooglemapsgeocoder](https://user-images.githubusercontent.com/30344224/35185574-e7b32d40-fe41-11e7-8067-b39753f87a35.png)

**Comment by safeimuslim** [comment]
same problem, how to fix it?

**Comment by zhso** [comment]
try the 3.0.1 version, already replace all http to https, for some reason, part of interface provider doesn't support the https version, it's wired, that's why i use http before.

**Comment by moseslucas** [comment]
Though I resolved it with using the google api instead, I will still try the latest version. Thanks
